### ISSUE TITLE
Cannot package as a Windows project

### ISSUE THREAD

**Issue by jimsimonz** [googlevr/poly-toolkit-unreal#1]
Plugin works great in the editor but has compile errors when packaged.
Tested as a Windows 64Bit shipping build, 4.18.1. Error log:

 C:\UnrealProjects\poly\HelloPoly\Plugins\PolyToolkit\Source\PolyToolkit\Private\HttpDownload.cpp(18): warning C4458: declaration of 'File' hides class member
UATHelper: Packaging (Windows (64-bit)):   c:\unrealprojects\poly\hellopoly\plugins\polytoolkit\source\polytoolkit\private\HttpDownload.h(38): note: see declaration of 'UHttpDownload::File'
UATHelper: Packaging (Windows (64-bit)):   C:\UnrealProjects\poly\HelloPoly\Plugins\PolyToolkit\Source\PolyToolkit\Private\HttpDownload.cpp(18): warning C4458: declaration of 'AssetName' hides class member
UATHelper: Packaging (Windows (64-bit)):   c:\unrealprojects\poly\hellopoly\plugins\polytoolkit\source\polytoolkit\private\HttpDownload.h(39): note: see declaration of 'UHttpDownload::AssetName'
UATHelper: Packaging (Windows (64-bit)):   C:\UnrealProjects\poly\HelloPoly\Plugins\PolyToolkit\Source\PolyToolkit\Private\HttpDownload.cpp(18): warning C4458: declaration of 'PolyToolkit' hides class member
UATHelper: Packaging (Windows (64-bit)):   c:\unrealprojects\poly\hellopoly\plugins\polytoolkit\source\polytoolkit\private\HttpDownload.h(41): note: see declaration of 'UHttpDownload::PolyToolkit'
UATHelper: Packaging (Windows (64-bit)):   C:\UnrealProjects\poly\HelloPoly\Plugins\PolyToolkit\Source\PolyToolkit\ThirdParty\gltf2-loader\ext\json.hpp(5788): error C4577: 'noexcept' used with no exception handling mode specified; termination on exception is not guaranteed. Specify /EHsc
UATHelper: Packaging (Windows (64-bit)):   C:\UnrealProjects\poly\HelloPoly\Plugins\PolyToolkit\Source\PolyToolkit\ThirdParty\gltf2-loader\ext\json.hpp(5113): error C4577: 'noexcept' used with no exception handling mode specified; termination on exception is not guaranteed. Specify /EHsc
UATHelper: Packaging (Windows (64-bit)):   C:\UnrealProjects\poly\HelloPoly\Plugins\PolyToolkit\Source\PolyToolkit\ThirdParty\gltf2-loader\ext\json.hpp(4791): error C4577: 'noexcept' used with no exception handling mode specified; termination on exception is not guaranteed. Specify /EHsc
UATHelper: Packaging (Windows (64-bit)):   C:\UnrealProjects\poly\HelloPoly\Plugins\PolyToolkit\Source\PolyToolkit\ThirdParty\gltf2-loader\ext\json.hpp(4720): error C4577: 'noexcept' used with no exception handling mode specified; termination on exception is not guaranteed. Specify /EHsc
UATHelper: Packaging (Windows (64-bit)):   C:\UnrealProjects\poly\HelloPoly\Plugins\PolyToolkit\Source\PolyToolkit\ThirdParty\gltf2-loader\ext\json.hpp(3013): error C4577: 'noexcept' used with no exception handling mode specified; termination on exception is not guaranteed. Specify /EHsc
UATHelper: Packaging (Windows (64-bit)):   C:\UnrealProjects\poly\HelloPoly\Plugins\PolyToolkit\Source\PolyToolkit\ThirdParty\gltf2-loader\ext\json.hpp(2991): error C4577: 'noexcept' used with no exception handling mode specified; termination on exception is not guaranteed. Specify /EHsc
UATHelper: Packaging (Windows (64-bit)):   C:\UnrealProjects\poly\HelloPoly\Plugins\PolyToolkit\Source\PolyToolkit\ThirdParty\gltf2-loader\ext\json.hpp(2969): error C4577: 'noexcept' used with no exception handling mode specified; termination on exception is not guaranteed. Specify /EHsc
UATHelper: Packaging (Windows (64-bit)):   C:\UnrealProjects\poly\HelloPoly\Plugins\PolyToolkit\Source\PolyToolkit\ThirdParty\gltf2-loader\ext\json.hpp(2862): error C4577: 'noexcept' used with no exception handling mode specified; termination on exception is not guaranteed. Specify /EHsc
UATHelper: Packaging (Windows (64-bit)):   C:\UnrealProjects\poly\HelloPoly\Plugins\PolyToolkit\Source\PolyToolkit\ThirdParty\gltf2-loader\ext\json.hpp(2832): error C4577: 'noexcept' used with no exception handling mode specified; termination on exception is not guaranteed. Specify /EHsc
UATHelper: Packaging (Windows (64-bit)):   C:\UnrealProjects\poly\HelloPoly\Plugins\PolyToolkit\Source\PolyToolkit\ThirdParty\gltf2-loader\ext\json.hpp(1990): error C4577: 'noexcept' used with no exception handling mode specified; termination on exception is not guaranteed. Specify /EHsc
UATHelper: Packaging (Windows (64-bit)):   C:\UnrealProjects\poly\HelloPoly\Plugins\PolyToolkit\Source\PolyToolkit\ThirdParty\gltf2-loader\ext\json.hpp(8650): error C4577: 'noexcept' used with no exception handling mode specified; termination on exception is not guaranteed. Specify /EHsc
UATHelper: Packaging (Windows (64-bit)):   C:\UnrealProjects\poly\HelloPoly\Plugins\PolyToolkit\Source\PolyToolkit\ThirdParty\gltf2-loader\ext\json.hpp(9033): error C4577: 'noexcept' used with no exception handling mode specified; termination on exception is not guaranteed. Specify /EHsc
UATHelper: Packaging (Windows (64-bit)):   C:\UnrealProjects\poly\HelloPoly\Plugins\PolyToolkit\Source\PolyToolkit\ThirdParty\gltf2-loader\ext\json.hpp(8996): error C4577: 'noexcept' used with no exception handling mode specified; termination on exception is not guaranteed. Specify /EHsc
UATHelper: Packaging (Windows (64-bit)):   C:\UnrealProjects\poly\HelloPoly\Plugins\PolyToolkit\Source\PolyToolkit\ThirdParty\gltf2-loader\ext\json.hpp(8970): error C4577: 'noexcept' used with no exception handling mode specified; termination on exception is not guaranteed. Specify /EHsc
UATHelper: Packaging (Windows (64-bit)):   C:\UnrealProjects\poly\HelloPoly\Plugins\PolyToolkit\Source\PolyToolkit\ThirdParty\gltf2-loader\ext\json.hpp(8917): error C4577: 'noexcept' used with no exception handling mode specified; termination on exception is not guaranteed. Specify /EHsc
UATHelper: Packaging (Windows (64-bit)):   C:\UnrealProjects\poly\HelloPoly\Plugins\PolyToolkit\Source\PolyToolkit\ThirdParty\gltf2-loader\ext\json.hpp(2947): error C4577: 'noexcept' used with no exception handling mode specified; termination on exception is not guaranteed. Specify /EHsc
UATHelper: Packaging (Windows (64-bit)):   C:\UnrealProjects\poly\HelloPoly\Plugins\PolyToolkit\Source\PolyToolkit\ThirdParty\gltf2-loader\ext\json.hpp(2891): error C4577: 'noexcept' used with no exception handling mode specified; termination on exception is not guaranteed. Specify /EHsc
UATHelper: Packaging (Windows (64-bit)):   C:\UnrealProjects\poly\HelloPoly\Plugins\PolyToolkit\Source\PolyToolkit\ThirdParty\gltf2-loader\ext\json.hpp(2810): error C4577: 'noexcept' used with no exception handling mode specified; termination on exception is not guaranteed. Specify /EHsc
UATHelper: Packaging (Windows (64-bit)):   C:\UnrealProjects\poly\HelloPoly\Plugins\PolyToolkit\Source\PolyToolkit\ThirdParty\gltf2-loader\ext\json.hpp(2592): error C4577: 'noexcept' used with no exception handling mode specified; termination on exception is not guaranteed. Specify /EHsc
UATHelper: Packaging (Windows (64-bit)):   C:\UnrealProjects\poly\HelloPoly\Plugins\PolyToolkit\Source\PolyToolkit\ThirdParty\gltf2-loader\ext\json.hpp(8760): error C4577: 'noexcept' used with no exception handling mode specified; termination on exception is not guaranteed. Specify /EHsc
UATHelper: Packaging (Windows (64-bit)):   C:\UnrealProjects\poly\HelloPoly\Plugins\PolyToolkit\Source\PolyToolkit\ThirdParty\gltf2-loader\ext\json.hpp(8639): error C4577: 'noexcept' used with no exception handling mode specified; termination on exception is not guaranteed. Specify /EHsc
UATHelper: Packaging (Windows (64-bit)):   C:\UnrealProjects\poly\HelloPoly\Plugins\PolyToolkit\Source\PolyToolkit\ThirdParty\gltf2-loader\ext\json.hpp(8633): error C4577: 'noexcept' used with no exception handling mode specified; termination on exception is not guaranteed. Specify /EHsc
UATHelper: Packaging (Windows (64-bit)):   C:\UnrealProjects\poly\HelloPoly\Plugins\PolyToolkit\Source\PolyToolkit\ThirdParty\gltf2-loader\ext\json.hpp(8627): error C4577: 'noexcept' used with no exception handling mode specified; termination on exception is not guaranteed. Specify /EHsc
UATHelper: Packaging (Windows (64-bit)):   C:\UnrealProjects\poly\HelloPoly\Plugins\PolyToolkit\Source\PolyToolkit\ThirdParty\gltf2-loader\ext\json.hpp(3040): error C4577: 'noexcept' used with no exception handling mode specified; termination on exception is not guaranteed. Specify /EHsc
UATHelper: Packaging (Windows (64-bit)):   C:\UnrealProjects\poly\HelloPoly\Plugins\PolyToolkit\Source\PolyToolkit\ThirdParty\gltf2-loader\ext\json.hpp(2555): error C4577: 'noexcept' used with no exception handling mode specified; termination on exception is not guaranteed. Specify /EHsc
UATHelper: Packaging (Windows (64-bit)):   C:\UnrealProjects\poly\HelloPoly\Plugins\PolyToolkit\Source\PolyToolkit\ThirdParty\gltf2-loader\ext\json.hpp(1737): error C4577: 'noexcept' used with no exception handling mode specified; termination on exception is not guaranteed. Specify /EHsc
UATHelper: Packaging (Windows (64-bit)):   C:\UnrealProjects\poly\HelloPoly\Plugins\PolyToolkit\Source\PolyToolkit\ThirdParty\gltf2-loader\ext\json.hpp(8147): error C4577: 'noexcept' used with no exception handling mode specified; termination on exception is not guaranteed. Specify /EHsc
UATHelper: Packaging (Windows (64-bit)):   C:\UnrealProjects\poly\HelloPoly\Plugins\PolyToolkit\Source\PolyToolkit\ThirdParty\gltf2-loader\ext\json.hpp(1743): error C4577: 'noexcept' used with no exception handling mode specified; termination on exception is not guaranteed. Specify /EHsc
UATHelper: Packaging (Windows (64-bit)):   C:\UnrealProjects\poly\HelloPoly\Plugins\PolyToolkit\Source\PolyToolkit\ThirdParty\gltf2-loader\ext\json.hpp(1741): error C4577: 'noexcept' used with no exception handling mode specified; termination on exception is not guaranteed. Specify /EHsc
UATHelper: Packaging (Windows (64-bit)):   C:\UnrealProjects\poly\HelloPoly\Plugins\PolyToolkit\Source\PolyToolkit\ThirdParty\gltf2-loader\ext\json.hpp(1739): error C4577: 'noexcept' used with no exception handling mode specified; termination on exception is not guaranteed. Specify /EHsc
UATHelper: Packaging (Windows (64-bit)):   C:\UnrealProjects\poly\HelloPoly\Plugins\PolyToolkit\Source\PolyToolkit\ThirdParty\gltf2-loader\ext\json.hpp(9632): error C4577: 'noexcept' used with no exception handling mode specified; termination on exception is not guaranteed. Specify /EHsc
UATHelper: Packaging (Windows (64-bit)):   C:\UnrealProjects\poly\HelloPoly\Plugins\PolyToolkit\Source\PolyToolkit\ThirdParty\gltf2-loader\ext\json.hpp(3063): error C4577: 'noexcept' used with no exception handling mode specified; termination on exception is not guaranteed. Specify /EHsc
UATHelper: Packaging (Windows (64-bit)):   C:\UnrealProjects\poly\HelloPoly\Plugins\PolyToolkit\Source\PolyToolkit\ThirdParty\gltf2-loader\ext\json.hpp(3439): error C4577: 'noexcept' used with no exception handling mode specified; termination on exception is not guaranteed. Specify /EHsc
UATHelper: Packaging (Windows (64-bit)):   C:\UnrealProjects\poly\HelloPoly\Plugins\PolyToolkit\Source\PolyToolkit\ThirdParty\gltf2-loader\ext\json.hpp(3165): error C4577: 'noexcept' used with no exception handling mode specified; termination on exception is not guaranteed. Specify /EHsc
UATHelper: Packaging (Windows (64-bit)):   C:\UnrealProjects\poly\HelloPoly\Plugins\PolyToolkit\Source\PolyToolkit\ThirdParty\gltf2-loader\ext\json.hpp(3153): error C4577: 'noexcept' used with no exception handling mode specified; termination on exception is not guaranteed. Specify /EHsc
UATHelper: Packaging (Windows (64-bit)):   C:\UnrealProjects\poly\HelloPoly\Plugins\PolyToolkit\Source\PolyToolkit\ThirdParty\gltf2-loader\ext\json.hpp(3141): error C4577: 'noexcept' used with no exception handling mode specified; termination on exception is not guaranteed. Specify /EHsc
UATHelper: Packaging (Windows (64-bit)):   C:\UnrealProjects\poly\HelloPoly\Plugins\PolyToolkit\Source\PolyToolkit\ThirdParty\gltf2-loader\ext\json.hpp(3129): error C4577: 'noexcept' used with no exception handling mode specified; termination on exception is not guaranteed. Specify /EHsc
UATHelper: Packaging (Windows (64-bit)):   C:\UnrealProjects\poly\HelloPoly\Plugins\PolyToolkit\Source\PolyToolkit\ThirdParty\gltf2-loader\ext\json.hpp(3117): error C4577: 'noexcept' used with no exception handling mode specified; termination on exception is not guaranteed. Specify /EHsc
UATHelper: Packaging (Windows (64-bit)):   C:\UnrealProjects\poly\HelloPoly\Plugins\PolyToolkit\Source\PolyToolkit\ThirdParty\gltf2-loader\ext\json.hpp(2919): error C4577: 'noexcept' used with no exception
 HelloPoly.cpp
UATHelper: Packaging (Windows (64-bit)):   ERROR: UBT ERROR: Failed to produce item: C:\UnrealProjects\poly\HelloPoly\Plugins\PolyToolkit\Binaries\Win64\UE4-PolyToolkit-Win64-Shipping.lib

**Comment by btco** [comment]
Fixed. Please download this patch release:
https://github.com/googlevr/poly-toolkit-unreal/releases/tag/v1.0.1

**Comment by jimsimonz** [comment]
Great thanks, confirmed here.

Best,
Jim
